# Generated by Django 2.0.7 on 2018-07-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
