STATUS_OK = 200
STATUS_FORBIDDEN = 403
STATUS_NOT_FOUND = 404
STATUS_UNKNOWN_METHOD = 405

STATUS_MAP = {
    STATUS_OK: 'OK',
    STATUS_FORBIDDEN: 'Forbidden',
    STATUS_NOT_FOUND: 'Not Found',
    STATUS_UNKNOWN_METHOD: 'Unknown Method'
}

